
export const lembagaData = [
  {
    id: 1,
    nama: 'Yayasan Rumah Kita Surabaya',
    telepon: '089520078733',
    kapasitas_pria: 18,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 10,
    alamat: 'Jl. Ngagel Madya II / 9 Surabaya',
    pic: 'Fendi H',
    email: 'rumahkitasby86@gmail.com',
    foto: require('../assets/yayasan_rumah_kita.jpeg'),
  },
  {
    id: 2,
    nama: 'Yayasan Orbit Surabaya',
    telepon: '082245948605',
    kapasitas_pria: 24,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 80,
    alamat: 'Jl. Margorejo Indah Utara Blok B-922 Margorejo, Surabaya',
    pic: 'Munib',
    email: 'orbit.foundation@yahoo.com',
    foto: require('../assets/yayasan_orbit.jpeg'),
  },
  {
    id: 3,
    nama: 'Plato Foundation',
    telepon: '081330351599',
    kapasitas_pria: 12,
    kapasitas_wanita: 12,
    kapasitas_rawat_jalan: 0,
    alamat: 'Jalan Cipta Menanggal V No. 16, Surabaya 60234',
    pic: 'Dita Amalia',
    email: 'plato.found@gmail.com',
    foto: require('../assets/yayasan_plato_surabaya.jpeg'),
  },
  {
    id: 4,
    nama: 'Yayasan LRPPN-BI Surabaya',
    telepon: '08123263524',
    kapasitas_pria: 25,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 50,
    alamat: 'Jl. Khairil Anwar 23 Surabaya',
    pic: 'Drs. Siswanto',
    email: 'pantilrppnsurabaya@gmail.com',
    foto: require('../assets/yayasan_lrppn.jpeg'),
  },
  {
    id: 5,
    nama: 'Yayasan Rumah Merah Putih Surabaya',
    telepon: '081213623393',
    kapasitas_pria: 25,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 100,
    alamat: 'Jl. Rungkut Menanggal Blok X-19 Rt.009 Rw. 004 Kel. Rungkut Menanggal Kec. Gunung Anyar Kota Surabaya',
    pic: 'Zulfikar Sharif',
    email: 'Mako2rungkut@gmail.com',
    foto: require('../assets/yayasan_rumah_merah_putih_2.jpg'),
  },
  {
    id: 6,
    nama: 'Yayasan Ashefa Griya Pusaka Surabaya',
    telepon: '085959591822',
    kapasitas_pria: 25,
    kapasitas_wanita: 5,
    kapasitas_rawat_jalan: 20,
    alamat: 'Jl Kutisari XIA no 1 RT 08 RW 05 Surabaya',
    pic: 'Jimmy',
    email: 'fpratiwisuryaningrums@gmail.com',
    foto: require('../assets/yayasan_ashefa_griya_pusaka.jpeg'),
  },
  {
    id: 7,
    nama: 'RSJ Menur Surabaya',
    telepon: '081330305585',
    kapasitas_pria: 44,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 0,
    alamat: 'Jl. Raya Menur No. 120 Surabaya',
    pic: 'Diyah',
    email: 'rsj.menur@gmail.com',
    foto: require('../assets/rs_menur.jpeg'),
  },
  {
    id: 8,
    nama: 'Klinik Pratama BNN Kota Surabaya',
    telepon: '081231878822',
    kapasitas_pria: 0,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 100,
    alamat: 'Jl. ngagel Madya V no. 22 Surabaya',
    pic: 'dr. singgih',
    email: 'rehab.bnnksby@gmail.com',
    foto: require('../assets/klinik_pratama1.jpg'),
  },
  {
    id: 9,
    nama: 'Yayasan Omah Sehat Bersinar',
    telepon: '085785966639',
    kapasitas_pria: 30,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 30,
    alamat: 'Ruko No. 31-32, Jl. Jemur Andayani No. 50',
    pic: 'Farita Sari D.',
    email: 'omahsehatbersinarosb@gmail.com',
    foto: require('../assets/yayasan_omah_sehat_bersinar.jpeg'),
  },
  {
    id: 10,
    nama: 'Subdirektorat Mitigasi Crisis Center',
    telepon: '085194932460',
    kapasitas_pria: 0,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 10,
    alamat: 'Jl. Lidah Wetan, Lidah Wetan, Kec. Lakarsantri, Surabaya',
    pic: 'Wiryo Nuryono',
    email: 'smccu@unesa.ac.id',
    foto: require('../assets/smcc_unesa.jpeg'),
  },
];

export const getLembagaLimit = (limit) => {
  return lembagaData.slice(0, limit);
};

export const getAllLembaga = () => {
  return lembagaData;
};
