import { PHOTO_URLS } from '../config/photoUrls';

export const lembagaData = [
  {
    id: 1,
    nama: 'Yayasan Rumah Kita Surabaya',
    telepon: '089520078733',
    kapasitas_pria: 18,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 10,
    alamat: 'Jl. Ngagel Madya II / 9 Surabaya',
    pic: 'Fendi H',
    email: 'rumahkitasby86@gmail.com',
    foto: PHOTO_URLS.YAYASAN_RUMAH_KITA_JPEG,
    kapasitas: 28,
    terisi: 15,
  },
  {
    id: 2,
    nama: 'Yayasan Orbit Surabaya',
    telepon: '082245948605',
    kapasitas_pria: 24,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 80,
    alamat: 'Jl. Margorejo Indah Utara Blok B-922 Margorejo, Surabaya',
    pic: 'Munib',
    email: 'orbit.foundation@yahoo.com',
    foto: PHOTO_URLS.YAYASAN_ORBIT_JPEG,
    kapasitas: 104,
    terisi: 68,
  },
  {
    id: 3,
    nama: 'Plato Foundation',
    telepon: '081330351599',
    kapasitas_pria: 12,
    kapasitas_wanita: 12,
    kapasitas_rawat_jalan: 0,
    alamat: 'Jalan Cipta Menanggal V No. 16, Surabaya 60234',
    pic: 'Dita Amalia',
    email: 'plato.found@gmail.com',
    foto: PHOTO_URLS.YAYASAN_PLATO_SURABAYA_JPEG,
    kapasitas: 24,
    terisi: 20,
  },
  {
    id: 4,
    nama: 'Yayasan LRPPN-BI Surabaya',
    telepon: '08123263524',
    kapasitas_pria: 25,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 50,
    alamat: 'Jl. Khairil Anwar 23 Surabaya',
    pic: 'Drs. Siswanto',
    email: 'pantilrppnsurabaya@gmail.com',
    foto: PHOTO_URLS.YAYASAN_LRPPN_JPEG,
    kapasitas: 75,
    terisi: 42,
  },
  {
    id: 5,
    nama: 'Yayasan Rumah Merah Putih Surabaya',
    telepon: '081213623393',
    kapasitas_pria: 25,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 100,
    alamat: 'Jl. Rungkut Menanggal Blok X-19 Rt.009 Rw. 004 Kel. Rungkut Menanggal Kec. Gunung Anyar Kota Surabaya',
    pic: 'Zulfikar Sharif',
    email: 'Mako2rungkut@gmail.com',
    foto: PHOTO_URLS.YAYASAN_RUMAH_MERAH_PUTIH_2_JPG,
    kapasitas: 125,
    terisi: 88,
  },
  {
    id: 6,
    nama: 'Yayasan Ashefa Griya Pusaka Surabaya',
    telepon: '085959591822',
    kapasitas_pria: 25,
    kapasitas_wanita: 5,
    kapasitas_rawat_jalan: 20,
    alamat: 'Jl Kutisari XIA no 1 RT 08 RW 05 Surabaya',
    pic: 'Jimmy',
    email: 'fpratiwisuryaningrums@gmail.com',
    foto: PHOTO_URLS.YAYASAN_ASHEFA_GRIYA_PUSAKA_JPEG,
    kapasitas: 50,
    terisi: 35,
  },
  {
    id: 7,
    nama: 'RSJ Menur Surabaya',
    telepon: '081330305585',
    kapasitas_pria: 44,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 0,
    alamat: 'Jl. Raya Menur No. 120 Surabaya',
    pic: 'Diyah',
    email: 'rsj.menur@gmail.com',
    foto: PHOTO_URLS.RS_MENUR_JPEG,
    kapasitas: 44,
    terisi: 39,
  },
  {
    id: 8,
    nama: 'Klinik Pratama BNN Kota Surabaya',
    telepon: '081231878822',
    kapasitas_pria: 0,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 100,
    alamat: 'Jl. ngagel Madya V no. 22 Surabaya',
    pic: 'dr. singgih',
    email: 'rehab.bnnksby@gmail.com',
    foto: PHOTO_URLS.KLINIK_PRATAMA1_JPG,
    kapasitas: 100,
    terisi: 62,
  },
  {
    id: 9,
    nama: 'Yayasan Omah Sehat Bersinar',
    telepon: '085785966639',
    kapasitas_pria: 30,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 30,
    alamat: 'Ruko No. 31-32, Jl. Jemur Andayani No. 50',
    pic: 'Farita Sari D.',
    email: 'omahsehatbersinarosb@gmail.com',
    foto: PHOTO_URLS.YAYASAN_OMAH_SEHAT_BERSINAR_JPEG,
    kapasitas: 60,
    terisi: 45,
  },
  {
    id: 10,
    nama: 'Subdirektorat Mitigasi Crisis Center',
    telepon: '085194932460',
    kapasitas_pria: 0,
    kapasitas_wanita: 0,
    kapasitas_rawat_jalan: 10,
    alamat: 'Jl. Lidah Wetan, Lidah Wetan, Kec. Lakarsantri, Surabaya',
    pic: 'Wiryo Nuryono',
    email: 'smccu@unesa.ac.id',
    foto: PHOTO_URLS.SMCC_UNESA_JPEG,
    kapasitas: 10,
    terisi: 7,
  },
];

export const getLembagaLimit = (limit) => {
  return lembagaData.slice(0, limit);
};

export const getAllLembaga = () => {
  return lembagaData;
};
