/**
 * Supabase Storage URLs untuk semua foto assets
 * Auto-generated by uploadAssets.js
 * Generated at: 2025-12-30T07:20:00.559Z
 */

export const PHOTO_URLS = {
  "BK0338_JPG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/BK0338.jpg",
  "CEGAHAN_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/CEGAHAN.jpeg",
  "COVER_JPG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/Cover.jpg",
  "COVER_2_JPG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/Cover_2.jpg",
  "DETEKSI_JPG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/deteksi.jpg",
  "EDUKASI_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/edukasi.jpeg",
  "HIMPUNAN_JPG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/Himpunan.jpg",
  "KLINIK_PRATAMA1_JPG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/klinik_pratama1.jpg",
  "LOGO_SMENGGI_PNG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/logo%20smenggi.png",
  "LOGO_BNN_PNG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/logo_bnn.png",
  "LOGO_SEMANGGI_PNG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/logo_semanggi.png",
  "MAP_SURABAYA_PNG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/map_surabaya.png",
  "RS_MENUR_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/rs_menur.jpeg",
  "SEMANGGI_PNG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/Semanggi.png",
  "SMCC_UNESA_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/smcc_unesa.jpeg",
  "YAYASAN_ASHEFA_GRIYA_PUSAKA_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_ashefa_griya_pusaka.jpeg",
  "YAYASAN_LRPPN_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_lrppn.jpeg",
  "YAYASAN_OMAH_SEHAT_BERSINAR_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_omah_sehat_bersinar.jpeg",
  "YAYASAN_ORBIT_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_orbit.jpeg",
  "YAYASAN_PLATO_SURABAYA_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_plato_surabaya.jpeg",
  "YAYASAN_RUMAH_KITA_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_rumah_kita.jpeg",
  "YAYASAN_RUMAH_MERAH_PUTIH_2_JPG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_rumah_merah_putih_2.jpg",
  "YAYASAN_UNESA_JPEG": "https://izpnubluaeboflbdqenw.supabase.co/storage/v1/object/public/bnn-photos/assets/yayasan_unesa.jpeg"
};

// Helper function untuk get foto URL
export const getPhotoUrl = (fileName) => {
  const key = fileName.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
  return PHOTO_URLS[key] || null;
};

export default PHOTO_URLS;
