/**
 * Script untuk upload semua foto dari folder assets ke Supabase Storage
 * 
 * Cara menjalankan:
 * node scripts/uploadAssets.js
 */

const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = 'https://izpnubluaeboflbdqenw.supabase.co';
// Menggunakan service_role key untuk upload (hanya untuk script ini)
const SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cG51Ymx1YWVib2ZsYmRxZW53Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzA3MzkyNywiZXhwIjoyMDgyNjQ5OTI3fQ.C81fiB13NVPJf1gKSYYG9yIgzB856DYjJ7wJ9A6ayU8';
const STORAGE_BUCKET = 'bnn-photos';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// Initialize storage bucket (skip, bucket harus dibuat manual di dashboard)
async function initializeStorage() {
  console.log('✅ Assuming storage bucket "bnn-photos" already exists in Supabase dashboard');
  console.log('⚠️  If upload fails, please create bucket manually at:');
  console.log('   https://supabase.com/dashboard/project/izpnubluaeboflbdqenw/storage/buckets');
  console.log('   - Bucket name: bnn-photos');
  console.log('   - Public bucket: Yes');
  console.log('   - File size limit: 5MB\n');
  return true;
}

// Upload single file
async function uploadFile(filePath, fileName) {
  try {
    const fileBuffer = fs.readFileSync(filePath);
    const storagePath = `assets/${fileName}`;
    
    console.log(`📤 Uploading: ${fileName}...`);
    
    const { data, error } = await supabase.storage
      .from(STORAGE_BUCKET)
      .upload(storagePath, fileBuffer, {
        cacheControl: '3600',
        upsert: true,
        contentType: getContentType(fileName)
      });
    
    if (error) {
      console.error(`❌ Error uploading ${fileName}:`, error.message);
      return null;
    }
    
    // Get public URL
    const { data: urlData } = supabase.storage
      .from(STORAGE_BUCKET)
      .getPublicUrl(storagePath);
    
    console.log(`✅ Uploaded: ${fileName} -> ${urlData.publicUrl}`);
    return { fileName, url: urlData.publicUrl };
  } catch (error) {
    console.error(`❌ Exception uploading ${fileName}:`, error.message);
    return null;
  }
}

// Get content type based on file extension
function getContentType(fileName) {
  const ext = path.extname(fileName).toLowerCase();
  const contentTypes = {
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.png': 'image/png',
    '.gif': 'image/gif'
  };
  return contentTypes[ext] || 'image/jpeg';
}

// Main upload function
async function uploadAllAssets() {
  console.log('🚀 Starting asset upload to Supabase...\n');
  
  // Initialize storage
  const initialized = await initializeStorage();
  if (!initialized) {
    console.error('❌ Failed to initialize storage. Aborting.');
    return;
  }
  
  console.log('');
  
  // Get all files from assets folder
  const assetsDir = path.join(__dirname, '..', 'assets');
  const files = fs.readdirSync(assetsDir);
  
  // Filter image files
  const imageFiles = files.filter(file => {
    const ext = path.extname(file).toLowerCase();
    return ['.jpg', '.jpeg', '.png', '.gif'].includes(ext);
  });
  
  console.log(`📦 Found ${imageFiles.length} image files\n`);
  
  // Upload all files
  const results = [];
  for (const file of imageFiles) {
    const filePath = path.join(assetsDir, file);
    const result = await uploadFile(filePath, file);
    if (result) {
      results.push(result);
    }
    // Small delay to avoid rate limiting
    await new Promise(resolve => setTimeout(resolve, 200));
  }
  
  console.log('\n📊 Upload Summary:');
  console.log(`✅ Successfully uploaded: ${results.length}/${imageFiles.length} files`);
  
  // Generate photoUrls.js file
  console.log('\n📝 Generating photoUrls.js...');
  generatePhotoUrlsFile(results);
  
  console.log('\n✅ All done! Check config/photoUrls.js for the URL mappings.');
}

// Generate photoUrls.js file
function generatePhotoUrlsFile(results) {
  const urlMappings = results.reduce((acc, { fileName, url }) => {
    const key = fileName.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
    acc[key] = url;
    return acc;
  }, {});
  
  const content = `/**
 * Supabase Storage URLs untuk semua foto assets
 * Auto-generated by uploadAssets.js
 * Generated at: ${new Date().toISOString()}
 */

export const PHOTO_URLS = ${JSON.stringify(urlMappings, null, 2)};

// Helper function untuk get foto URL
export const getPhotoUrl = (fileName) => {
  const key = fileName.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
  return PHOTO_URLS[key] || null;
};

export default PHOTO_URLS;
`;
  
  const outputPath = path.join(__dirname, '..', 'config', 'photoUrls.js');
  fs.writeFileSync(outputPath, content);
  console.log('✅ Generated config/photoUrls.js');
}

// Run the script
uploadAllAssets().catch(error => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
